# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cerveza', models.CharField(max_length=200)),
                ('observaciones', models.TextField()),
                ('foto', models.FileField(upload_to='fotos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pub', models.CharField(max_length=200)),
                ('direccion_pub', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Votaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(default=0)),
                ('cerveza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBApp.Cerveza')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBApp.Pub')),
                ('usuario', models.ManyToManyField(to='BBApp.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pub',
            name='cerveza',
            field=models.ManyToManyField(through='BBApp.Votaciones', to='BBApp.Cerveza'),
        ),
    ]
