# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cerveza', models.CharField(max_length=200)),
                ('observaciones', models.TextField()),
                ('foto', models.FileField(upload_to='BBApp/images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pub', models.CharField(max_length=200)),
                ('direccion_pub', models.CharField(max_length=200)),
                ('cerveza', models.ManyToManyField(to='BBApp.Cerveza')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=200)),
                ('estado_civil', models.EmailField(blank=True, max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(default=0)),
                ('cerveza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBApp.Cerveza')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBApp.Pub')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBApp.Usuario')),
            ],
        ),
    ]
