# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveza',
            name='foto',
            field=models.FileField(upload_to='BBApp/images/%Y/%m/%d'),
        ),
    ]
