# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBApp', '0003_usuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='cerveza_preferida',
        ),
    ]
