# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBApp', '0005_auto_20181025_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votaciones',
            old_name='usuario',
            new_name='user',
        ),
    ]
